apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  annotations:
  name: argocon-demo
  namespace: argocd
spec:
  activeCommitStatuses:
  - key: argocd-health
  environments:
  - branch: environments/development
    autoMerge: false
  - branch: environments/staging
  - branch: environments/production
  gitRepositoryRef:
    name: argocon-demo
